### ISSUE TITLE
leaked API keys

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [steveattewell/osm-ai-map#4]
Hi steve,

just wanted to let you know, that your maptiler API key is still valid and you probably want to remove that from your repo or regenerate it.

If you want to remove it from the history, you can squash the commit latest commit to 0ad3152077963dea0d4f435b27ed8c8f5de068af (where you introduced them) and force push to the main branch. (people who forked the repo before will still have that commit though.)

If it's possible to re-generate the maptiler API key that would be the best solution.

The leaked chatGPT API key seems to be invalid.

**Comment by steveattewell** [comment]
Fixed, Key revoked. thank you

**Comment by TheGreatRefrigerator** [comment]
you're welcome
